### ISSUE TITLE
IAM auth questions

### ISSUE THREAD

**Issue by 1fish2** [CovertLab/borealis#1]
There are setup questions for the `borealis-fireworker` service, and currently the service can't delete its GCE VM instance using the technique from Sisyphus:

```
>>> from cloud import gcp
>>> gcp.delete_this_vm()
GCE VM "jhm-0" shutting down...
ERROR: (gcloud.compute.instances.delete) Could not fetch resource:
 - Insufficient Permission: Request had insufficient authentication scopes.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fireworker/borealis/cloud/gcp.py", line 73, in delete_this_vm
    fp.run_cmd(['gcloud', '--quiet', 'compute', 'instances', 'delete',
  File "/home/fireworker/borealis/util/filepath.py", line 49, in run_cmd
    out = subprocess.run(
  File "/home/fireworker/.pyenv/versions/3.8.1/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['gcloud', '--quiet', 'compute', 'instances', 'delete', 'jhm-0', '--zone', 'us-west1-b']' returned non-zero exit status 1.
```

- [x] How to grant the needed permissions to fix that? Make a new `.cloud.json` file? How? Keep the file and rename the `fireworker` user to `sisyphus`?
- [x] Document set up instructions -- esp. the scopes and service account -- so people can use the `borealis-fireworker` service in their own GCP projects.
- [x] How to make the `borealis-fireworker.service` initialize `pyenv`? (I hacked it by making `boot.sh` source `.bash_aliases`.)
- [ ] Can/should we configure worker VM scopes and service-account via an Instance Template instead of in the call to `gcloud compute instances create`? Otherwise, move those strings from the source code to a config file.

**Comment by 1fish2** [comment]
The permissions, scopes, and setup steps have been fixed and documented as of 2602f56d7249ba40d17016c36484144f7e68062c.

I'll move the Instance Template item to the Project board.
